### ISSUE TITLE
Mantissa support for letsencrypt

### ISSUE THREAD

**Issue by mithrandi** [twisted/mantissa#40]
Activating this for a particular TLS port would take care of periodically renewing the certificate, most likely using `tls-sni-01` verification so that the challenges can be handled through the same port, and restarting the port with the new certificate, for a completely "handsfree" operational experience.

**Comment by glyph** [comment]
:100:

**Comment by glyph** [comment]
You don't actually need to "restart" the port, because it is at least hypothetically possible to start responding to [`clientConnectionForTLS`](https://twistedmatrix.com/documents/15.5.0/api/twisted.internet.interfaces.IOpenSSLClientConnectionCreator.html#clientConnectionForTLS) and `serverConnectionForTLS` with connection objects bound to new contexts.

**Comment by mithrandi** [comment]
I guess assuming we're using txsni for this, we just need to swap out the certificate in txsni's certificate mapping structure.

**Comment by mithrandi** [comment]
You can use the txacme `le:` endpoint for this (sort of, see twisted/txacme#129 and #54)
